/**
 * Sprite atlas 帧规格，供 gen-atlas.js 和 process-sprite.js 共用。
 */

export const SPRITE_SPECS = {
  maxwell:   { w: 64, h: 96, frames: ['maxwell_idle','maxwell_walk_0','maxwell_walk_1','maxwell_walk_2','maxwell_walk_3','maxwell_jump','maxwell_fall','maxwell_dead'] },
  // biped/quadruped 为历史家族 atlas 预留规格（renderer===id 迁移后不再被词条引用，
  // 保留作多帧动画参考；creature 物种已按独立 id 单帧注册，见下方各家族段）。
  biped:     { w: 64, h: 96, frames: ['biped_idle','biped_walk_0','biped_walk_1','biped_walk_2','biped_walk_3','biped_jump','biped_fall'] },
  quadruped: { w: 80, h: 64, frames: ['quadruped_idle','quadruped_walk_0','quadruped_walk_1','quadruped_walk_2','quadruped_walk_3','quadruped_jump'] },
  bird:      { w: 48, h: 48, frames: ['bird_idle','bird_fly_0','bird_fly_1','bird_fly_2','bird_fly_3'] },
  fish:      { w: 48, h: 48, frames: ['fish_idle','fish_swim_0','fish_swim_1','fish_swim_2','fish_swim_3'] },
  tentacled: { w: 64, h: 64, frames: ['tentacled_idle','tentacled_move_0','tentacled_move_1','tentacled_move_2','tentacled_move_3'] },
  car:       { w: 96, h: 64, frames: ['car_idle','car_move_0','car_move_1','car_move_2','car_move_3'] },
  fire:      { w: 48, h: 64, frames: ['fire_0','fire_1','fire_2','fire_3'] },
  water:     { w: 48, h: 48, frames: ['water_0','water_1','water_2','water_3'] },
  steam:     { w: 40, h: 56, frames: ['steam_0','steam_1','steam_2'] },
  starite:   { w: 64, h: 64, frames: ['starite_0','starite_1','starite_2','starite_3'] },
  sword:     { w: 32, h: 80, frames: ['sword_idle'] },
  knife:     { w: 24, h: 56, frames: ['knife_idle'] },
  gun:       { w: 56, h: 40, frames: ['gun_idle'] },
  rope:      { w: 16, h: 80, frames: ['rope_idle'] },
  box:       { w: 80, h: 80, frames: ['box_idle'] },
  wheel:     { w: 32, h: 32, frames: ['wheel_idle'] },
  apple:     { w: 40, h: 44, frames: ['apple_idle'] },
  meat:      { w: 48, h: 36, frames: ['meat_idle'] },
  tree:      { w: 96, h: 128, frames: ['tree_idle'] },
  stone:     { w: 48, h: 40, frames: ['stone_idle'] },
  bush:      { w: 56, h: 48, frames: ['bush_idle'] },
  flower:    { w: 32, h: 56, frames: ['flower_idle'] },
  fence:     { w: 40, h: 56, frames: ['fence_idle'] },
  stalactite:{ w: 32, h: 80, frames: ['stalactite_idle'] },
  lantern:   { w: 32, h: 64, frames: ['lantern_idle'] },
  totem:     { w: 56, h: 128, frames: ['totem_idle'] },
  'ruin-pillar': { w: 80, h: 160, frames: ['ruin-pillar_idle'] },

  // 生物
  penguin:    { w: 36, h: 40, frames: ['penguin_idle'] },
  snake:      { w: 48, h: 16, frames: ['snake_idle'] },
  frog:       { w: 32, h: 24, frames: ['frog_idle'] },
  // 元素
  ice:        { w: 40, h: 40, frames: ['ice_idle'] },
  snow:       { w: 36, h: 36, frames: ['snow_idle'] },
  lightning:  { w: 24, h: 64, frames: ['lightning_idle'] },
  sand:       { w: 32, h: 32, frames: ['sand_idle'] },
  mud:        { w: 40, h: 40, frames: ['mud_idle'] },
  // 物品/容器
  fridge:     { w: 48, h: 96, frames: ['fridge_idle'] },
  wood:       { w: 64, h: 20, frames: ['wood_idle'] },
  metal:      { w: 48, h: 24, frames: ['metal_idle'] },
  glass:      { w: 40, h: 40, frames: ['glass_idle'] },
  ball:       { w: 36, h: 36, frames: ['ball_idle'] },
  chair:      { w: 36, h: 48, frames: ['chair_idle'] },
  table:      { w: 64, h: 40, frames: ['table_idle'] },
  key:        { w: 12, h: 32, frames: ['key_idle'] },
  coin:       { w: 24, h: 24, frames: ['coin_idle'] },
  brick:      { w: 40, h: 20, frames: ['brick_idle'] },
  paper:      { w: 28, h: 36, frames: ['paper_idle'] },
  pillow:     { w: 48, h: 28, frames: ['pillow_idle'] },
  mirror:     { w: 28, h: 48, frames: ['mirror_idle'] },
  bone:       { w: 40, h: 12, frames: ['bone_idle'] },
  clock:      { w: 36, h: 36, frames: ['clock_idle'] },
  vase:       { w: 28, h: 48, frames: ['vase_idle'] },
  candle:     { w: 16, h: 40, frames: ['candle_idle'] },
  // 食物
  bread:      { w: 40, h: 28, frames: ['bread_idle'] },
  bomb:       { w: 32, h: 36, frames: ['bomb_idle'] },
  bow:        { w: 16, h: 56, frames: ['bow_idle'] },
  balloon:    { w: 28, h: 36, frames: ['balloon_idle'] },
  hammer:     { w: 14, h: 48, frames: ['hammer_idle'] },
  shovel:     { w: 14, h: 64, frames: ['shovel_idle'] },
  ladder:     { w: 28, h: 96, frames: ['ladder_idle'] },
  bucket:     { w: 32, h: 36, frames: ['bucket_idle'] },
  umbrella:   { w: 56, h: 48, frames: ['umbrella_idle'] },
  book:       { w: 36, h: 44, frames: ['book_idle'] },
  cheese:     { w: 36, h: 28, frames: ['cheese_idle'] },
  egg:        { w: 24, h: 30, frames: ['egg_idle'] },
  carrot:     { w: 16, h: 40, frames: ['carrot_idle'] },
  banana:     { w: 28, h: 20, frames: ['banana_idle'] },
  cake:       { w: 40, h: 32, frames: ['cake_idle'] },
  axe:        { w: 36, h: 40, frames: ['axe_idle'] },
  spear:      { w: 10, h: 80, frames: ['spear_idle'] },
  arrow:      { w: 6, h: 40, frames: ['arrow_idle'] },
  shield:     { w: 40, h: 56, frames: ['shield_idle'] },
  // 植物
  grass:      { w: 40, h: 20, frames: ['grass_idle'] },
  cactus:     { w: 32, h: 56, frames: ['cactus_idle'] },
  log:        { w: 64, h: 24, frames: ['log_idle'] },
  // 载具
  bicycle:    { w: 56, h: 40, frames: ['bicycle_idle'] },
  boat:       { w: 80, h: 32, frames: ['boat_idle'] },
  plane:      { w: 96, h: 40, frames: ['plane_idle'] },
  // 工具
  pickaxe:    { w: 40, h: 48, frames: ['pickaxe_idle'] },
  torch:      { w: 12, h: 56, frames: ['torch_idle'] },
  fishingrod: { w: 8, h: 80, frames: ['fishingrod_idle'] },
  magnet:     { w: 24, h: 48, frames: ['magnet_idle'] },

  // ---- 待接入专用 sprite：characters（独立 sprite，每物种一张图）----
  starfish              : { w:  48, h:  48, frames: ['starfish_idle'] },
  urchin                : { w:  40, h:  40, frames: ['urchin_idle'] },
  snail                 : { w:  56, h:  40, frames: ['snail_idle'] },
  slug                  : { w:  44, h:  20, frames: ['slug_idle'] },
  clam                  : { w:  40, h:  32, frames: ['clam_idle'] },
  oyster                : { w:  40, h:  32, frames: ['oyster_idle'] },
  coral                 : { w:  72, h:  72, frames: ['coral_idle'] },
  sponge                : { w:  44, h:  44, frames: ['sponge_idle'] },
  slime                 : { w:  48, h:  40, frames: ['slime_idle'] },
  mimic                 : { w:  52, h:  52, frames: ['mimic_idle'] },
  worm                  : { w:  96, h:  40, frames: ['worm_idle'] },
  willowisp             : { w:  28, h:  28, frames: ['willowisp_idle'] },

  // ---- 雀形目 passerine ----
  crow                  : { w:  44, h:  40, frames: ['crow_idle'] },
  sparrow               : { w:  32, h:  28, frames: ['sparrow_idle'] },
  robin                 : { w:  32, h:  32, frames: ['robin_idle'] },
  canary                : { w:  32, h:  32, frames: ['canary_idle'] },
  finch                 : { w:  32, h:  28, frames: ['finch_idle'] },
  magpie                : { w:  44, h:  40, frames: ['magpie_idle'] },
  jay                   : { w:  40, h:  36, frames: ['jay_idle'] },
  cardinal              : { w:  40, h:  32, frames: ['cardinal_idle'] },
  pigeon                : { w:  40, h:  32, frames: ['pigeon_idle'] },
  woodpecker            : { w:  40, h:  40, frames: ['woodpecker_idle'] },
  hummingbird           : { w:  28, h:  28, frames: ['hummingbird_idle'] },

  // ---- 猛禽 raptor ----
  eagle                 : { w:  52, h:  48, frames: ['eagle_idle'] },
  owl                   : { w:  44, h:  44, frames: ['owl_idle'] },
  vulture               : { w:  52, h:  52, frames: ['vulture_idle'] },
  bat                   : { w:  44, h:  40, frames: ['bat_idle'] },

  // ---- 鸡形目 galliform ----
  chicken               : { w:  40, h:  40, frames: ['chicken_idle'] },
  chick                 : { w:  28, h:  28, frames: ['chick_idle'] },
  peacock               : { w:  64, h:  64, frames: ['peacock_idle'] },
  turkey                : { w:  52, h:  52, frames: ['turkey_idle'] },
  quail                 : { w:  32, h:  32, frames: ['quail_idle'] },
  pheasant              : { w:  52, h:  48, frames: ['pheasant_idle'] },
  grouse                : { w:  48, h:  44, frames: ['grouse_idle'] },

  // ---- 雁形目 anseriform ----
  duck                  : { w:  44, h:  40, frames: ['duck_idle'] },
  swan                  : { w:  64, h:  52, frames: ['swan_idle'] },
  goose                 : { w:  52, h:  48, frames: ['goose_idle'] },
  peep                  : { w:  40, h:  32, frames: ['peep_idle'] },

  // ---- 涉禽 ciconiiform ----
  flamingo              : { w:  44, h:  76, frames: ['flamingo_idle'] },
  stork                 : { w:  48, h:  64, frames: ['stork_idle'] },
  heron                 : { w:  48, h:  64, frames: ['heron_idle'] },
  crane                 : { w:  48, h:  76, frames: ['crane_idle'] },

  // ---- 鹦形目 psittaciform ----
  parrot                : { w:  48, h:  44, frames: ['parrot_idle'] },
  parakeet              : { w:  40, h:  32, frames: ['parakeet_idle'] },
  macaw                 : { w:  52, h:  52, frames: ['macaw_idle'] },
  cockatoo              : { w:  48, h:  48, frames: ['cockatoo_idle'] },

  // ---- 走禽 ratite ----
  ostrich               : { w:  64, h:  76, frames: ['ostrich_idle'] },
  cassowary             : { w:  64, h:  76, frames: ['cassowary_idle'] },
  'kiwi-bird'           : { w:  44, h:  44, frames: ['kiwi-bird_idle'] },

  // ---- 神话鸟 mythic-bird ----
  phoenix               : { w:  64, h:  64, frames: ['phoenix_idle'] },
  harpy                 : { w:  52, h:  64, frames: ['harpy_idle'] },
  mothman               : { w:  64, h:  76, frames: ['mothman_idle'] },
  gargoyle              : { w:  64, h:  64, frames: ['gargoyle_idle'] },
  cockatrice            : { w:  64, h:  52, frames: ['cockatrice_idle'] },
  fairy                 : { w:  32, h:  44, frames: ['fairy_idle'] },

  // ---- 犬科 canid ----
  dog                   : { w:  64, h:  44, frames: ['dog_idle'] },
  wolf                  : { w:  76, h:  52, frames: ['wolf_idle'] },
  fox                   : { w:  64, h:  48, frames: ['fox_idle'] },
  hyena                 : { w:  68, h:  52, frames: ['hyena_idle'] },
  puppy                 : { w:  44, h:  32, frames: ['puppy_idle'] },

  // ---- 猫科 felid ----
  cat                   : { w:  52, h:  40, frames: ['cat_idle'] },
  tiger                 : { w:  84, h:  60, frames: ['tiger_idle'] },
  lion                  : { w:  84, h:  60, frames: ['lion_idle'] },
  leopard               : { w:  76, h:  52, frames: ['leopard_idle'] },
  cheetah               : { w:  76, h:  52, frames: ['cheetah_idle'] },
  jaguar                : { w:  84, h:  60, frames: ['jaguar_idle'] },
  kitten                : { w:  40, h:  28, frames: ['kitten_idle'] },

  // ---- 熊科 ursid ----
  bear                  : { w:  96, h:  76, frames: ['bear_idle'] },
  grizzly               : { w:  96, h:  76, frames: ['grizzly_idle'] },
  'polar-bear'          : { w:  96, h:  76, frames: ['polar-bear_idle'] },
  cub                   : { w:  52, h:  44, frames: ['cub_idle'] },
  panda                 : { w:  76, h:  64, frames: ['panda_idle'] },
  sloth                 : { w:  52, h:  48, frames: ['sloth_idle'] },
  raccoon               : { w:  52, h:  44, frames: ['raccoon_idle'] },
  badger                : { w:  60, h:  40, frames: ['badger_idle'] },

  // ---- 鼬科 mustelid ----
  otter                 : { w:  52, h:  32, frames: ['otter_idle'] },
  beaver                : { w:  60, h:  40, frames: ['beaver_idle'] },
  mole                  : { w:  40, h:  28, frames: ['mole_idle'] },

  // ---- 鳍足目 pinniped ----
  seal                  : { w:  76, h:  48, frames: ['seal_idle'] },
  walrus                : { w:  96, h:  60, frames: ['walrus_idle'] },
  manatee               : { w:  96, h:  52, frames: ['manatee_idle'] },

  // ---- 牛科 bovid ----
  cow                   : { w:  84, h:  60, frames: ['cow_idle'] },
  goat                  : { w:  64, h:  52, frames: ['goat_idle'] },
  sheep                 : { w:  60, h:  52, frames: ['sheep_idle'] },
  bison                 : { w:  96, h:  68, frames: ['bison_idle'] },
  yak                   : { w:  84, h:  64, frames: ['yak_idle'] },
  ibex                  : { w:  84, h:  68, frames: ['ibex_idle'] },
  antelope              : { w:  84, h:  68, frames: ['antelope_idle'] },
  gazelle               : { w:  72, h:  60, frames: ['gazelle_idle'] },
  'donkey-calf'         : { w:  60, h:  44, frames: ['donkey-calf_idle'] },
  lamb                  : { w:  44, h:  40, frames: ['lamb_idle'] },

  // ---- 猪科 suid ----
  pig                   : { w:  64, h:  48, frames: ['pig_idle'] },
  boar                  : { w:  76, h:  52, frames: ['boar_idle'] },
  piglet                : { w:  44, h:  32, frames: ['piglet_idle'] },

  // ---- 鹿科 cervid ----
  deer                  : { w:  84, h:  68, frames: ['deer_idle'] },
  elk                   : { w:  96, h:  84, frames: ['elk_idle'] },
  moose                 : { w: 108, h:  96, frames: ['moose_idle'] },
  giraffe               : { w:  96, h: 144, frames: ['giraffe_idle'] },

  // ---- 马科 equid ----
  horse                 : { w:  92, h:  68, frames: ['horse_idle'] },
  zebra                 : { w:  92, h:  68, frames: ['zebra_idle'] },
  donkey                : { w:  80, h:  64, frames: ['donkey_idle'] },
  mule                  : { w:  84, h:  64, frames: ['mule_idle'] },
  foal                  : { w:  68, h:  52, frames: ['foal_idle'] },
  camel                 : { w: 104, h:  80, frames: ['camel_idle'] },
  llama                 : { w:  80, h:  80, frames: ['llama_idle'] },

  // ---- 厚皮目 pachyderm ----
  elephant              : { w: 116, h:  84, frames: ['elephant_idle'] },
  hippo                 : { w: 104, h:  64, frames: ['hippo_idle'] },
  rhino                 : { w: 104, h:  64, frames: ['rhino_idle'] },

  // ---- 啮齿目 rodent ----
  squirrel              : { w:  40, h:  32, frames: ['squirrel_idle'] },
  mouse                 : { w:  32, h:  28, frames: ['mouse_idle'] },
  porcupine             : { w:  60, h:  44, frames: ['porcupine_idle'] },
  chinchilla            : { w:  40, h:  32, frames: ['chinchilla_idle'] },
  guineapig             : { w:  44, h:  32, frames: ['guineapig_idle'] },
  hamster               : { w:  32, h:  28, frames: ['hamster_idle'] },
  gerbil                : { w:  40, h:  28, frames: ['gerbil_idle'] },
  rabbit                : { w:  40, h:  32, frames: ['rabbit_idle'] },
  hedgehog              : { w:  44, h:  32, frames: ['hedgehog_idle'] },
  echidna               : { w:  48, h:  40, frames: ['echidna_idle'] },
  armadillo             : { w:  60, h:  40, frames: ['armadillo_idle'] },
  platypus              : { w:  60, h:  32, frames: ['platypus_idle'] },

  // ---- 有袋目 marsupial ----
  kangaroo              : { w:  64, h:  84, frames: ['kangaroo_idle'] },
  koala                 : { w:  52, h:  48, frames: ['koala_idle'] },
  opossum               : { w:  48, h:  32, frames: ['opossum_idle'] },

  // ---- 灵长目 primate ----
  monkey                : { w:  48, h:  60, frames: ['monkey_idle'] },
  baboon                : { w:  64, h:  64, frames: ['baboon_idle'] },
  lemur                 : { w:  48, h:  52, frames: ['lemur_idle'] },
  'monkey-small'        : { w:  48, h:  60, frames: ['monkey-small_idle'] },

  // ---- 蜥蜴 squamate ----
  lizard                : { w:  56, h:  28, frames: ['lizard_idle'] },
  gecko                 : { w:  48, h:  24, frames: ['gecko_idle'] },
  iguana                : { w:  80, h:  48, frames: ['iguana_idle'] },
  chameleon            : { w:  56, h:  40, frames: ['chameleon_idle'] },
  basilisk              : { w:  80, h:  40, frames: ['basilisk_idle'] },

  // ---- 鳄目 crocodilian ----
  alligator             : { w: 112, h:  40, frames: ['alligator_idle'] },
  crocodile             : { w: 112, h:  40, frames: ['crocodile_idle'] },

  // ---- 龟鳖目 testudine ----
  turtle                : { w:  56, h:  48, frames: ['turtle_idle'] },
  'turtle-sea'          : { w:  80, h:  56, frames: ['turtle-sea_idle'] },

  // ---- 两栖 anuran ----
  toad                  : { w:  48, h:  36, frames: ['toad_idle'] },
  newt                  : { w:  48, h:  24, frames: ['newt_idle'] },
  salamander            : { w:  52, h:  28, frames: ['salamander_idle'] },

  // ---- 鲸目 cetacean ----
  whale                 : { w: 128, h:  64, frames: ['whale_idle'] },
  dolphin               : { w:  84, h:  44, frames: ['dolphin_idle'] },

  // ---- 软骨鱼 selachian ----
  shark                 : { w:  96, h:  40, frames: ['shark_idle'] },
  ray                   : { w:  76, h:  44, frames: ['ray_idle'] },

  // ---- 鳗形 eel ----
  eel                   : { w:  84, h:  24, frames: ['eel_idle'] },

  // ---- 神话四足 mythic-quad ----
  dragon                : { w: 176, h: 116, frames: ['dragon_idle'] },
  unicorn               : { w: 116, h:  88, frames: ['unicorn_idle'] },
  griffin               : { w: 132, h: 104, frames: ['griffin_idle'] },
  wyvern                : { w: 144, h: 104, frames: ['wyvern_idle'] },
  centaur               : { w: 132, h: 104, frames: ['centaur_idle'] },
  nessie                : { w: 112, h:  48, frames: ['nessie_idle'] },
  kelpie                : { w: 116, h:  88, frames: ['kelpie_idle'] },
  pegasus               : { w: 116, h:  88, frames: ['pegasus_idle'] },
  hippogriff            : { w: 132, h: 104, frames: ['hippogriff_idle'] },
  manticore             : { w: 116, h:  88, frames: ['manticore_idle'] },
  chimera               : { w: 132, h: 104, frames: ['chimera_idle'] },
  'unicorn-dark'        : { w: 116, h:  88, frames: ['unicorn-dark_idle'] },

  // ---- 人形 humanoid ----
  human                 : { w:  36, h:  68, frames: ['human_idle'] },
  mermaid               : { w:  48, h:  68, frames: ['mermaid_idle'] },
  goblin                : { w:  40, h:  48, frames: ['goblin_idle'] },
  orc                   : { w:  48, h:  68, frames: ['orc_idle'] },
  zombie                : { w:  40, h:  68, frames: ['zombie_idle'] },
  skeleton              : { w:  40, h:  68, frames: ['skeleton_idle'] },
  vampire               : { w:  44, h:  68, frames: ['vampire_idle'] },
  mummy                 : { w:  44, h:  68, frames: ['mummy_idle'] },
  demon                 : { w:  60, h:  80, frames: ['demon_idle'] },
  alien                 : { w:  44, h:  60, frames: ['alien_idle'] },
  robot                 : { w:  44, h:  68, frames: ['robot_idle'] },
  cyborg                : { w:  44, h:  68, frames: ['cyborg_idle'] },
  android               : { w:  44, h:  68, frames: ['android_idle'] },
  lich                  : { w:  44, h:  68, frames: ['lich_idle'] },

  // ---- 巨人族 giantkin ----
  minotaur              : { w:  76, h:  84, frames: ['minotaur_idle'] },
  cyclops               : { w:  76, h:  96, frames: ['cyclops_idle'] },
  ogre                  : { w:  76, h:  84, frames: ['ogre_idle'] },
  troll                 : { w:  64, h:  84, frames: ['troll_idle'] },
  werewolf              : { w:  76, h:  84, frames: ['werewolf_idle'] },
  yeti                  : { w:  76, h:  84, frames: ['yeti_idle'] },
  sasquatch             : { w:  76, h:  84, frames: ['sasquatch_idle'] },
  golem                 : { w:  76, h:  84, frames: ['golem_idle'] },
  giant                 : { w:  76, h: 104, frames: ['giant_idle'] },
  ent                   : { w:  76, h: 104, frames: ['ent_idle'] },
  titan                 : { w:  84, h: 128, frames: ['titan_idle'] },

  // ---- 精类 fae ----
  imp                   : { w:  36, h:  44, frames: ['imp_idle'] },
  nymph                 : { w:  40, h:  60, frames: ['nymph_idle'] },
  elf                   : { w:  40, h:  68, frames: ['elf_idle'] },
  dwarf                 : { w:  40, h:  48, frames: ['dwarf_idle'] },
  gnome                 : { w:  36, h:  44, frames: ['gnome_idle'] },
  satyr                 : { w:  44, h:  68, frames: ['satyr_idle'] },
  homunculus            : { w:  36, h:  44, frames: ['homunculus_idle'] },
  leprechaun            : { w:  36, h:  48, frames: ['leprechaun_idle'] },
  gremlin               : { w:  36, h:  44, frames: ['gremlin_idle'] },

  // ---- 灵体 spirit ----
  ghost                 : { w:  48, h:  64, frames: ['ghost_idle'] },
  angel                 : { w:  52, h:  76, frames: ['angel_idle'] },
  wraith                : { w:  48, h:  76, frames: ['wraith_idle'] },
  banshee               : { w:  48, h:  76, frames: ['banshee_idle'] },
  selkie                : { w:  52, h:  64, frames: ['selkie_idle'] },

  // ---- 兽人 beastman ----
  fishman               : { w:  52, h:  76, frames: ['fishman_idle'] },
  insectoid             : { w:  52, h:  64, frames: ['insectoid_idle'] },
  naga                  : { w:  64, h:  76, frames: ['naga_idle'] },

  // ---- 待接入专用 sprite：effects ----
  'cloud-element'       : { w:  76, h:  40, frames: ['cloud-element_idle'] },
  snowfall              : { w:  44, h:  44, frames: ['snowfall_idle'] },
  hail                  : { w:  32, h:  32, frames: ['hail_idle'] },
  tornado               : { w:  56, h:  96, frames: ['tornado_idle'] },
  wind                  : { w:  56, h:  20, frames: ['wind_idle'] },
  frost                 : { w:  60, h:  60, frames: ['frost_idle'] },
  rainbow               : { w: 120, h:  72, frames: ['rainbow_idle'] },
  ash                   : { w:  36, h:  36, frames: ['ash_idle'] },
  crystal               : { w:  48, h:  60, frames: ['crystal_idle'] },
  quartz                : { w:  48, h:  48, frames: ['quartz_idle'] },
  ore                   : { w:  40, h:  36, frames: ['ore_idle'] },
  coal                  : { w:  36, h:  24, frames: ['coal_idle'] },
  clay                  : { w:  40, h:  32, frames: ['clay_idle'] },
  chalk                 : { w:  28, h:  52, frames: ['chalk_idle'] },
  salt                  : { w:  32, h:  32, frames: ['salt_idle'] },
  sulfur                : { w:  32, h:  32, frames: ['sulfur_idle'] },
  tar                   : { w:  44, h:  32, frames: ['tar_idle'] },
  force                 : { w:  56, h:  56, frames: ['force_idle'] },
  void                  : { w:  56, h:  56, frames: ['void_idle'] },
  'shadow-element'      : { w:  48, h:  48, frames: ['shadow-element_idle'] },
  light                 : { w:  40, h:  56, frames: ['light_idle'] },

  // ---- 待接入专用 sprite：food ----
  grape                 : { w:  40, h:  48, frames: ['grape_idle'] },
  cherry                : { w:  32, h:  36, frames: ['cherry_idle'] },
  strawberry            : { w:  36, h:  40, frames: ['strawberry_idle'] },
  blueberry             : { w:  16, h:  16, frames: ['blueberry_idle'] },
  raspberry             : { w:  20, h:  24, frames: ['raspberry_idle'] },
  blackberry            : { w:  20, h:  24, frames: ['blackberry_idle'] },
  watermelon            : { w:  72, h:  48, frames: ['watermelon_idle'] },
  'orange-fruit'        : { w:  40, h:  40, frames: ['orange-fruit_idle'] },
  lemon                 : { w:  32, h:  24, frames: ['lemon_idle'] },
  lime                  : { w:  24, h:  24, frames: ['lime_idle'] },
  peach                 : { w:  40, h:  40, frames: ['peach_idle'] },
  pear                  : { w:  40, h:  56, frames: ['pear_idle'] },
  plum                  : { w:  24, h:  24, frames: ['plum_idle'] },
  mango                 : { w:  36, h:  32, frames: ['mango_idle'] },
  pineapple             : { w:  56, h:  72, frames: ['pineapple_idle'] },
  coconut               : { w:  36, h:  36, frames: ['coconut_idle'] },
  'kiwi-fruit'          : { w:  32, h:  24, frames: ['kiwi-fruit_idle'] },
  pomegranate           : { w:  48, h:  48, frames: ['pomegranate_idle'] },
  apricot               : { w:  36, h:  36, frames: ['apricot_idle'] },
  fig                   : { w:  40, h:  48, frames: ['fig_idle'] },
  date                  : { w:  20, h:  36, frames: ['date_idle'] },
  melon                 : { w:  44, h:  36, frames: ['melon_idle'] },
  pumpkin               : { w:  72, h:  60, frames: ['pumpkin_idle'] },
  tomato                : { w:  40, h:  40, frames: ['tomato_idle'] },
  cucumber              : { w:  44, h:  16, frames: ['cucumber_idle'] },
  pepper                : { w:  24, h:  48, frames: ['pepper_idle'] },
  corn                  : { w:  36, h:  72, frames: ['corn_idle'] },
  wheat                 : { w:  36, h:  52, frames: ['wheat_idle'] },
  rice                  : { w:  24, h:  24, frames: ['rice_idle'] },
  noodle                : { w:  48, h:  20, frames: ['noodle_idle'] },
  soup                  : { w:  44, h:  36, frames: ['soup_idle'] },
  pie                   : { w:  52, h:  36, frames: ['pie_idle'] },
  cookie                : { w:  32, h:  32, frames: ['cookie_idle'] },
  donut                 : { w:  40, h:  40, frames: ['donut_idle'] },
  candy                 : { w:  24, h:  24, frames: ['candy_idle'] },
  chocolate             : { w:  36, h:  24, frames: ['chocolate_idle'] },
  honey                 : { w:  32, h:  36, frames: ['honey_idle'] },
  jam                   : { w:  24, h:  32, frames: ['jam_idle'] },
  butter                : { w:  36, h:  24, frames: ['butter_idle'] },
  yogurt                : { w:  32, h:  36, frames: ['yogurt_idle'] },
  milk                  : { w:  24, h:  36, frames: ['milk_idle'] },
  juice                 : { w:  24, h:  36, frames: ['juice_idle'] },
  tea                   : { w:  24, h:  36, frames: ['tea_idle'] },
  coffee                : { w:  24, h:  36, frames: ['coffee_idle'] },
  wine                  : { w:  24, h:  36, frames: ['wine_idle'] },
  beer                  : { w:  24, h:  40, frames: ['beer_idle'] },

  // ---- 待接入专用 sprite：weapons ----
  mace                  : { w:  48, h:  72, frames: ['mace_idle'] },
  flail                 : { w:  60, h:  84, frames: ['flail_idle'] },
  halberd               : { w:  80, h:  84, frames: ['halberd_idle'] },
  scythe                : { w: 104, h:  60, frames: ['scythe_idle'] },
  club                  : { w:  28, h:  52, frames: ['club_idle'] },
  'staff-weapon'        : { w:  28, h:  84, frames: ['staff-weapon_idle'] },
  slingshot             : { w:  36, h:  48, frames: ['slingshot_idle'] },
  crossbow              : { w:  60, h:  48, frames: ['crossbow_idle'] },
  cannon                : { w:  60, h:  52, frames: ['cannon_idle'] },
  grenade               : { w:  36, h:  48, frames: ['grenade_idle'] },
  dynamite              : { w:  52, h:  40, frames: ['dynamite_idle'] },
  tnt                   : { w:  36, h:  24, frames: ['tnt_idle'] },
  whip                  : { w:  36, h:  68, frames: ['whip_idle'] },
  net                   : { w:  72, h:  72, frames: ['net_idle'] },
  blowgun               : { w:  36, h:  52, frames: ['blowgun_idle'] },
  shuriken              : { w:  40, h:  40, frames: ['shuriken_idle'] },
  chakram               : { w:  48, h:  48, frames: ['chakram_idle'] },
  boomerang             : { w:  48, h:  24, frames: ['boomerang_idle'] },

  // ---- 待接入专用 sprite：nature ----
  bamboo                : { w:  36, h:  84, frames: ['bamboo_idle'] },
  sunflower             : { w:  72, h: 120, frames: ['sunflower_idle'] },
  lavender              : { w:  48, h:  60, frames: ['lavender_idle'] },
  moss                  : { w:  48, h:  20, frames: ['moss_idle'] },
  fern                  : { w:  60, h:  72, frames: ['fern_idle'] },
  seaweed               : { w:  28, h:  76, frames: ['seaweed_idle'] },
  'pumpkin-plant'       : { w:  72, h:  36, frames: ['pumpkin-plant_idle'] },
  thorn                 : { w:  48, h:  48, frames: ['thorn_idle'] },
  reed                  : { w:  28, h:  68, frames: ['reed_idle'] },

  // ---- 待接入专用 sprite：vehicles ----
  'balloon-hot'         : { w:  84, h: 120, frames: ['balloon-hot_idle'] },
  rocket                : { w:  60, h: 144, frames: ['rocket_idle'] },
  ufo                   : { w:  68, h:  36, frames: ['ufo_idle'] },
  sleigh                : { w: 120, h:  48, frames: ['sleigh_idle'] },
  wheelbarrow           : { w:  84, h:  60, frames: ['wheelbarrow_idle'] },
  stroller              : { w:  72, h:  60, frames: ['stroller_idle'] },
  'crane-vehicle'       : { w: 144, h: 120, frames: ['crane-vehicle_idle'] },
  bulldozer             : { w: 144, h:  84, frames: ['bulldozer_idle'] },

  // ---- 待接入专用 sprite：tools ----
  screwdriver           : { w:  28, h:  40, frames: ['screwdriver_idle'] },
  wrench                : { w:  48, h:  24, frames: ['wrench_idle'] },
  pliers                : { w:  48, h:  24, frames: ['pliers_idle'] },
  scissors              : { w:  36, h:  60, frames: ['scissors_idle'] },
  saw                   : { w:  72, h:  36, frames: ['saw_idle'] },
  drill                 : { w:  48, h:  60, frames: ['drill_idle'] },
  chisel                : { w:  28, h:  40, frames: ['chisel_idle'] },
  file                  : { w:  28, h:  52, frames: ['file_idle'] },
  clamp                 : { w:  36, h:  48, frames: ['clamp_idle'] },
  level                 : { w:  72, h:  16, frames: ['level_idle'] },
  ruler                 : { w:  40, h:  16, frames: ['ruler_idle'] },
  'compass-tool'        : { w:  36, h:  52, frames: ['compass-tool_idle'] },
  trowel                : { w:  48, h:  24, frames: ['trowel_idle'] },
  'gloves-garden'       : { w:  48, h:  36, frames: ['gloves-garden_idle'] },
  sprinkler             : { w:  48, h:  48, frames: ['sprinkler_idle'] },
  hose                  : { w:  36, h:  68, frames: ['hose_idle'] },
  needle                : { w:  16, h:  32, frames: ['needle_idle'] },
  thread                : { w:  16, h:  52, frames: ['thread_idle'] },
  spool                 : { w:  36, h:  48, frames: ['spool_idle'] },
  loom                  : { w: 120, h:  96, frames: ['loom_idle'] },
  anvil                 : { w:  52, h:  36, frames: ['anvil_idle'] },
  bellows               : { w:  60, h:  48, frames: ['bellows_idle'] },
  whetstone             : { w:  60, h:  24, frames: ['whetstone_idle'] },
  'clamp-lamp'          : { w:  60, h:  72, frames: ['clamp-lamp_idle'] },
  goggles               : { w:  48, h:  24, frames: ['goggles_idle'] },
  apron                 : { w:  60, h:  72, frames: ['apron_idle'] },

  // ---- 待接入专用 sprite：objects ----
  couch                 : { w: 120, h:  60, frames: ['couch_idle'] },
  bed                   : { w: 144, h:  72, frames: ['bed_idle'] },
  drawer                : { w:  52, h:  24, frames: ['drawer_idle'] },
  shelf                 : { w:  68, h:  88, frames: ['shelf_idle'] },
  lamp                  : { w:  48, h:  72, frames: ['lamp_idle'] },
  fan                   : { w:  72, h:  84, frames: ['fan_idle'] },
  oven                  : { w:  60, h:  60, frames: ['oven_idle'] },
  microwave             : { w:  52, h:  40, frames: ['microwave_idle'] },
  toaster               : { w:  40, h:  32, frames: ['toaster_idle'] },
  tv                    : { w:  68, h:  52, frames: ['tv_idle'] },
  radio                 : { w:  44, h:  36, frames: ['radio_idle'] },
  phone                 : { w:  24, h:  44, frames: ['phone_idle'] },
  computer              : { w:  52, h:  44, frames: ['computer_idle'] },
  printer               : { w:  52, h:  40, frames: ['printer_idle'] },
  camera                : { w:  56, h:  40, frames: ['camera_idle'] },
  bin                   : { w:  36, h:  44, frames: ['bin_idle'] },
  basket                : { w:  60, h:  48, frames: ['basket_idle'] },
  barrel                : { w:  44, h:  60, frames: ['barrel_idle'] },
  cupboard              : { w:  60, h:  68, frames: ['cupboard_idle'] },
  wardrobe              : { w:  60, h:  88, frames: ['wardrobe_idle'] },
  rug                   : { w: 120, h:  24, frames: ['rug_idle'] },
  curtain               : { w:  72, h:  96, frames: ['curtain_idle'] },
  painting              : { w:  72, h:  84, frames: ['painting_idle'] },
  poster                : { w:  60, h:  84, frames: ['poster_idle'] },
  frame                 : { w:  60, h:  72, frames: ['frame_idle'] },
  sculpture             : { w:  60, h:  96, frames: ['sculpture_idle'] },
  trophy                : { w:  40, h:  72, frames: ['trophy_idle'] },
  medal                 : { w:  36, h:  48, frames: ['medal_idle'] },
  crown                 : { w:  60, h:  36, frames: ['crown_idle'] },
  scepter               : { w:  28, h:  68, frames: ['scepter_idle'] },
  gem                   : { w:  32, h:  36, frames: ['gem_idle'] },
  diamond               : { w:  36, h:  40, frames: ['diamond_idle'] },
  pearl                 : { w:  16, h:  16, frames: ['pearl_idle'] },
  ring                  : { w:  24, h:  24, frames: ['ring_idle'] },
  necklace              : { w:  36, h:  48, frames: ['necklace_idle'] },
  watch                 : { w:  32, h:  36, frames: ['watch_idle'] },
  glasses               : { w:  48, h:  16, frames: ['glasses_idle'] },
  'umbrella-rain'       : { w:  60, h:  84, frames: ['umbrella-rain_idle'] },
  'hat-top'             : { w:  56, h:  36, frames: ['hat-top_idle'] },
  cap                   : { w:  48, h:  32, frames: ['cap_idle'] },
  helmet                : { w:  48, h:  40, frames: ['helmet_idle'] },
  'crown-flower'        : { w:  56, h:  56, frames: ['crown-flower_idle'] },
  mask                  : { w:  40, h:  48, frames: ['mask_idle'] },
  shoe                  : { w:  40, h:  24, frames: ['shoe_idle'] },
  boot                  : { w:  40, h:  48, frames: ['boot_idle'] },
  glove                 : { w:  36, h:  40, frames: ['glove_idle'] },
  scarf                 : { w:  60, h:  24, frames: ['scarf_idle'] },
  tie                   : { w:  36, h:  40, frames: ['tie_idle'] },
  sock                  : { w:  32, h:  40, frames: ['sock_idle'] },
  dress                 : { w:  60, h:  84, frames: ['dress_idle'] },
  shirt                 : { w:  60, h:  60, frames: ['shirt_idle'] },
  pants                 : { w:  48, h:  72, frames: ['pants_idle'] },
  coat                  : { w:  60, h:  84, frames: ['coat_idle'] },
  robe                  : { w:  60, h:  96, frames: ['robe_idle'] },
  armor                 : { w:  60, h:  84, frames: ['armor_idle'] },
  backpack              : { w:  56, h:  64, frames: ['backpack_idle'] },
  purse                 : { w:  48, h:  40, frames: ['purse_idle'] },
  suitcase              : { w:  52, h:  40, frames: ['suitcase_idle'] },
  cart                  : { w:  96, h:  60, frames: ['cart_idle'] },
  wagon                 : { w: 120, h:  72, frames: ['wagon_idle'] },
  sign                  : { w:  72, h:  48, frames: ['sign_idle'] },
  'fence-stone'         : { w:  72, h:  84, frames: ['fence-stone_idle'] },
  gate                  : { w:  72, h:  96, frames: ['gate_idle'] },
  window                : { w:  52, h:  52, frames: ['window_idle'] },
  door                  : { w:  80, h:  84, frames: ['door_idle'] },
  stairs                : { w:  96, h: 120, frames: ['stairs_idle'] },
  elevator              : { w:  52, h:  68, frames: ['elevator_idle'] },
  escalator             : { w: 120, h:  72, frames: ['escalator_idle'] },
  fountain              : { w:  84, h:  96, frames: ['fountain_idle'] },
  statue                : { w:  60, h: 120, frames: ['statue_idle'] },
  pillar                : { w:  72, h:  84, frames: ['pillar_idle'] },
  arch                  : { w:  96, h: 120, frames: ['arch_idle'] },
  bridge                : { w: 144, h:  36, frames: ['bridge_idle'] },
  tower                 : { w:  84, h: 192, frames: ['tower_idle'] },
  castle                : { w: 192, h: 192, frames: ['castle_idle'] },
  cottage               : { w: 144, h: 120, frames: ['cottage_idle'] },
  tent                  : { w:  96, h:  84, frames: ['tent_idle'] },
  igloo                 : { w:  68, h:  52, frames: ['igloo_idle'] },
  well                  : { w:  72, h:  72, frames: ['well_idle'] },
  gravestone            : { w:  48, h:  72, frames: ['gravestone_idle'] },
  coffin                : { w:  60, h: 120, frames: ['coffin_idle'] },
  altar                 : { w:  96, h:  72, frames: ['altar_idle'] },
  'crystal-ball'        : { w:  60, h:  60, frames: ['crystal-ball_idle'] },
  potion                : { w:  36, h:  48, frames: ['potion_idle'] },
  scroll                : { w:  52, h:  40, frames: ['scroll_idle'] },
  wand                  : { w:  28, h:  68, frames: ['wand_idle'] },
  'crystal-shard'       : { w:  24, h:  36, frames: ['crystal-shard_idle'] },
  amulet                : { w:  32, h:  40, frames: ['amulet_idle'] },
  'totem-mini'          : { w:  60, h: 120, frames: ['totem-mini_idle'] },

  // ---- 装饰补充（Environment.buildDecorations 使用）----
  mushroom:    { w: 32, h: 40, frames: ['mushroom_idle'] },
  cloud:       { w: 64, h: 32, frames: ['cloud_idle'] },
  snowflake:   { w: 36, h: 36, frames: ['snowflake_idle'] },
};
